export const AGENTS = [
  {
    id: 'rob',
    name: 'Rob',
    role: 'principal_seo',
    title: 'Principal SEO',
    color: '#E74C3C',
    personality: 'Visionary SEO strategist. Deep expertise in technical SEO, algorithm updates, and large-scale site architecture.',
    capabilities: ['technical_seo', 'site_architecture', 'algorithm_analysis', 'seo_strategy', 'crawl_optimization'],
    state: 'idle',
    completedTasks: 0,
  },
  {
    id: 'mike',
    name: 'Mike',
    role: 'coo',
    title: 'COO',
    color: '#2C3E50',
    personality: 'Operations mastermind. Keeps projects on track, manages resources, and ensures client deliverables are met on time.',
    capabilities: ['project_management', 'resource_allocation', 'kpi_tracking', 'client_management', 'operations'],
    state: 'idle',
    completedTasks: 0,
  },
  {
    id: 'craig',
    name: 'Craig',
    role: 'seo_director',
    title: 'SEO Director',
    color: '#27AE60',
    personality: 'On-page and content SEO expert. Loves keyword research, content gap analysis, and building topic clusters.',
    capabilities: ['keyword_research', 'content_strategy', 'on_page_seo', 'topic_clusters', 'link_building'],
    state: 'idle',
    completedTasks: 0,
  },
  {
    id: 'leo',
    name: 'Leo',
    role: 'seo_director',
    title: 'SEO Director',
    color: '#8E44AD',
    personality: 'Local SEO and E-E-A-T specialist. Expert in GBP optimization, local pack rankings, and topical authority.',
    capabilities: ['local_seo', 'eeat_optimization', 'schema_markup', 'gbp_management', 'citation_building'],
    state: 'idle',
    completedTasks: 0,
  },
  {
    id: 'ewan',
    name: 'Ewan',
    role: 'head_of_seo',
    title: 'Head of SEO',
    color: '#F39C12',
    personality: 'Hands-on SEO leader. Bridges strategy and execution, mentors the team, spots quick wins.',
    capabilities: ['seo_leadership', 'account_oversight', 'quick_win_analysis', 'reporting', 'team_mentoring'],
    state: 'idle',
    completedTasks: 0,
  },
  {
    id: 'mya',
    name: 'Mya',
    role: 'account_manager',
    title: 'SEO Account Manager',
    color: '#E91E90',
    personality: 'Client-facing SEO expert. Translates technical SEO into business outcomes, manages client relationships.',
    capabilities: ['client_management', 'campaign_tracking', 'seo_reporting', 'stakeholder_comms', 'campaign_execution'],
    state: 'idle',
    completedTasks: 0,
  },
  {
    id: 'alex',
    name: 'Alex',
    role: 'data_engineer',
    title: 'Data Scientist & Engineer',
    color: '#3498DB',
    personality: 'Data wizard. Builds pipelines, automates reporting, and uncovers insights from crawl data and analytics.',
    capabilities: ['data_pipelines', 'log_analysis', 'seo_automation', 'predictive_modeling', 'dashboard_building'],
    state: 'idle',
    completedTasks: 0,
  },
  {
    id: 'ken',
    name: 'Ken',
    role: 'data_engineer',
    title: 'Data Scientist & Engineer',
    color: '#1ABC9C',
    personality: 'Infrastructure and tooling specialist. Expert in web scraping, API integrations, and internal SEO tools.',
    capabilities: ['web_scraping', 'api_integration', 'tool_building', 'etl_pipelines', 'seo_tooling'],
    state: 'idle',
    completedTasks: 0,
  },
];
