export const AGENTS = [
  {
    id: 'ada',
    name: 'Ada',
    role: 'planner',
    title: 'Project Manager',
    color: '#FF6B6B',
    personality: 'Organized, strategic, keeps everyone on track.',
    capabilities: ['task_planning', 'progress_tracking', 'delegation'],
    state: 'idle',
    completedTasks: 0,
  },
  {
    id: 'byte',
    name: 'Byte',
    role: 'researcher',
    title: 'Research Analyst',
    color: '#4ECDC4',
    personality: 'Curious, thorough, loves diving deep into topics.',
    capabilities: ['knowledge_search', 'summarization', 'fact_checking'],
    state: 'idle',
    completedTasks: 0,
  },
  {
    id: 'chip',
    name: 'Chip',
    role: 'coder',
    title: 'Senior Developer',
    color: '#45B7D1',
    personality: 'Focused, pragmatic, writes clean code.',
    capabilities: ['code_writing', 'debugging', 'refactoring'],
    state: 'idle',
    completedTasks: 0,
  },
  {
    id: 'dot',
    name: 'Dot',
    role: 'reviewer',
    title: 'Code Reviewer',
    color: '#96CEB4',
    personality: 'Detail-oriented, constructive, catches bugs others miss.',
    capabilities: ['code_review', 'security_audit', 'style_checking'],
    state: 'idle',
    completedTasks: 0,
  },
  {
    id: 'echo',
    name: 'Echo',
    role: 'tester',
    title: 'QA Engineer',
    color: '#FFEAA7',
    personality: 'Methodical, persistent, finds edge cases nobody thought of.',
    capabilities: ['test_writing', 'edge_case_analysis', 'regression_testing'],
    state: 'idle',
    completedTasks: 0,
  },
  {
    id: 'flux',
    name: 'Flux',
    role: 'documenter',
    title: 'Technical Writer',
    color: '#DDA0DD',
    personality: 'Clear communicator, empathetic, makes complex things simple.',
    capabilities: ['documentation', 'tutorial_writing', 'api_docs'],
    state: 'idle',
    completedTasks: 0,
  },
];
